[package]
name = "day08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
once_cell = "1.16.0"
itertools = "*"
indicatif = "0.17.7"

[[bin]]
name = "day08"
path = "day08.rs"
